[versions]
java = "24"
springBoot = "3.5.8"
telegrambots = "6.9.7.1"
postgresql = "42.7.3"
lombok = "1.18.42"
springDependencyManagement = "1.1.6"
httpclient = "4.5.14"
jib = "3.5.2"

[libraries]
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web", version.ref = "springBoot" }
spring-boot-starter-security = { module = "org.springframework.boot:spring-boot-starter-security", version.ref = "springBoot" }
spring-boot-starter-data-jpa = { module = "org.springframework.boot:spring-boot-starter-data-jpa", version.ref = "springBoot" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test", version.ref = "springBoot" }
spring-security-test = { module = "org.springframework.security:spring-security-test" }
liquibase-core = { module = "org.liquibase:liquibase-core" }
telegrambots-spring-boot-starter = { module = "org.telegram:telegrambots-spring-boot-starter", version.ref = "telegrambots" }

postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
httpclient = { module = "org.apache.httpcomponents:httpclient", version.ref = "httpclient" }

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "springBoot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "springDependencyManagement" }
jib = { id = "com.google.cloud.tools.jib", version.ref = "jib" }
