version: '3.8'

services:
  akira-postgres:
    container_name: akira-postgres
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: akira
      POSTGRES_USER: akira
      POSTGRES_PASSWORD: akira
    volumes:
      # - ./postgres-data:/var/lib/postgresql/data
      - ./certs:/etc/postgresql/certs:ro
    command: >
      sh -c "
      mkdir -p /var/lib/postgresql/run-certs &&
      cp /etc/postgresql/certs/server.crt /var/lib/postgresql/run-certs/server.crt &&
      cp /etc/postgresql/certs/server.key /var/lib/postgresql/run-certs/server.key &&
      chown postgres:postgres /var/lib/postgresql/run-certs/server.key &&
      chmod 600 /var/lib/postgresql/run-certs/server.key &&
      exec docker-entrypoint.sh postgres
      -c ssl=on
      -c ssl_cert_file=/var/lib/postgresql/run-certs/server.crt
      -c ssl_key_file=/var/lib/postgresql/run-certs/server.key
      "
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U akira"]
      interval: 10s
      timeout: 5s
      retries: 5

  akira-app:
    container_name: akira-app
    image: ${DOCKER_USERNAME:-yourusername}/akira:latest
    ports:
      - "8443:8443"
    environment:
      SPRING_DATASOURCE_PASSWORD: akira
      SPRING_SECURITY_USER_NAME: admin
      SPRING_SECURITY_USER_PASSWORD: admin
      # Сертификаты монтируются через volume, пути указываются через переменные окружения
      SERVER_SSL_CERTIFICATE: file:/app/certs/server.crt
      SERVER_SSL_CERTIFICATE_PRIVATE_KEY: file:/app/certs/server.key
    volumes:
      # Монтируем сертификаты из локальной директории (read-only)
      - ./certs:/app/certs:ro
    depends_on:
      akira-postgres:
        condition: service_healthy
    restart: unless-stopped

